#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "Release Loom — signature, notarisation, DMG"

# ── Stage 1 : prérequis ───────────────────────────────────────────────────
stage "Prérequis — Xcode et compte développeur"
say "La distribution hors Mac App Store exige un compte Apple Developer payant"
say "(ADR-0004 : Developer ID + notarisation)."
if command -v xcodebuild >/dev/null 2>&1; then
  say "✓ Xcode détecté : $(xcodebuild -version | head -1)"
else
  warn "Xcode introuvable — installe-le depuis l'App Store avant de continuer."
fi
open_url "https://developer.apple.com/account"
step "Vérifie que ton adhésion Apple Developer Program est active."
pause

# ── Stage 2 : certificat Developer ID ─────────────────────────────────────
stage "Certificat « Developer ID Application »"
say "Xcode → Réglages → Accounts → ton équipe → Manage Certificates…"
step "Clique + → « Developer ID Application » (s'il n'existe pas déjà)."
pause "Fait ? Entrée pour vérifier."
say "Identités de signature présentes :"
security find-identity -v -p codesigning | grep "Developer ID Application" || warn "aucune trouvée — le certificat n'est pas installé"
step "Copie l'identité complète, ex. : Developer ID Application: Ton Nom (TEAMID)"
ask LOOM_SIGN_IDENTITY "Colle l'identité de signature :"
write_env LOOM_SIGN_IDENTITY "$LOOM_SIGN_IDENTITY"

# ── Stage 3 : identifiant de bundle ───────────────────────────────────────
stage "Identifiant de bundle"
say "L'identifiant unique de l'app (reverse-DNS), ex. com.tondomaine.loom."
ask LOOM_BUNDLE_ID "Bundle ID :"
write_env LOOM_BUNDLE_ID "$LOOM_BUNDLE_ID"

# ── Stage 4 : build release et assemblage du .app ─────────────────────────
stage "Build release et assemblage de Loom.app"
say "Compilation SPM en release puis assemblage du bundle…"
swift build -c release
APP=dist/Loom.app
rm -rf "$APP"; mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp .build/release/LoomApp "$APP/Contents/MacOS/Loom"
cp .build/release/loom-hook "$APP/Contents/MacOS/loom-hook"
VERSION=$(git describe --tags --always 2>/dev/null || echo "0.1.0")
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleExecutable</key><string>Loom</string>
  <key>CFBundleIdentifier</key><string>${LOOM_BUNDLE_ID}</string>
  <key>CFBundleName</key><string>Loom</string>
  <key>CFBundleShortVersionString</key><string>${VERSION}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>14.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict></plist>
PLIST
say "✓ $APP assemblé (version ${VERSION})"
pause

# ── Stage 5 : signature Hardened Runtime ──────────────────────────────────
stage "Signature (Hardened Runtime, ADR-0004)"
codesign --force --options runtime --sign "$LOOM_SIGN_IDENTITY" "$APP/Contents/MacOS/loom-hook"
codesign --force --options runtime --sign "$LOOM_SIGN_IDENTITY" "$APP"
codesign --verify --deep --strict "$APP" && say "✓ signature vérifiée"
pause

# ── Stage 6 : identifiants de notarisation ────────────────────────────────
stage "Identifiants notarytool (mot de passe d'app)"
say "La notarisation utilise ton Apple ID + un mot de passe d'application."
open_url "https://account.apple.com/account/manage"
step "Connexion → Sécurité → Mots de passe d'app → + → nomme-le « loom-notary »."
ask APPLE_ID "Ton Apple ID (email) :"
ask APPLE_TEAM_ID "Ton Team ID (10 caractères, visible sur developer.apple.com/account) :"
ask_secret APPLE_APP_PASSWORD "Colle le mot de passe d'app (caché) :"
xcrun notarytool store-credentials loom-notary \
  --apple-id "$APPLE_ID" --team-id "$APPLE_TEAM_ID" --password "$APPLE_APP_PASSWORD"
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
say "✓ profil « loom-notary » enregistré dans le trousseau (le mot de passe n'est PAS écrit en clair)"

# ── Stage 7 : notarisation et staple ──────────────────────────────────────
stage "Notarisation Apple (quelques minutes)"
ditto -c -k --keepParent "$APP" dist/Loom.zip
xcrun notarytool submit dist/Loom.zip --keychain-profile loom-notary --wait
xcrun stapler staple "$APP"
spctl --assess --type execute "$APP" && say "✓ Gatekeeper accepte l'app"
pause

# ── Stage 8 : DMG ─────────────────────────────────────────────────────────
stage "Image disque de distribution"
rm -f dist/Loom.dmg
hdiutil create -volname "Loom" -srcfolder "$APP" -ov -format UDZO dist/Loom.dmg
say "✓ dist/Loom.dmg prêt à distribuer"
note "Sparkle (mises à jour auto) : étape ultérieure — génération de clés EdDSA"
note "et appcast auto-hébergé, à câbler quand un canal de distribution existera."
pause

finish
